version: "3"

services:
  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:${REDIS_IMAGE_VERSION}
    networks:
      - frappe_network

  redis-queue:
    image: redis:${REDIS_IMAGE_VERSION}
    networks:
      - frappe_network
    volumes:
      - redis-queue-data:/data

  backend:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_erpnext
    user: "frappe"
    networks:
      - frappe_network
    depends_on:
      - db
      - redis-cache
      - redis-queue
    volumes:
      - apps:/home/frappe/frappe-bench/apps
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: 9000

  create-site:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_create_site
    user: "frappe"
    networks:
      - frappe_network
    depends_on:
      - backend
      - db
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - apps:/home/frappe/frappe-bench/apps
    command: >
      bash -c "
      if [ ! -d /home/frappe/frappe-bench/sites/frontend ]; then
        bench new-site frontend \
          --mariadb-user-host-login-scope='%' \
          --admin-password=admin \
          --db-root-username=root \
          --db-root-password=admin \
          --install-app erpnext 
      else
        echo 'Site frontend already exists. Installing HRMS if missing...' &&
        bench get-app --branch version-15 hrms || true &&
        bench --site frontend install-app hrms || true &&
        bench --site frontend migrate
      fi
      "
    deploy:
      restart_policy:
        condition: none

  frontend:
    image: frappe/erpnext:${FRAPPE_ERPNEXT_IMAGE_VERSION}
    container_name: frappe_frontend
    networks:
      - frappe_network
    depends_on:
      - backend
    environment:
      BACKEND: backend:8000   # au lieu de 0.0.0.0:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: frontend
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m  
    ports:
      - "${FRONTEND_PORT_VAR}:8080"
    volumes:
      - apps:/home/frappe/frappe-bench/apps
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    command: ["nginx-entrypoint.sh"]

volumes:
  db-data:
  redis-queue-data:
  apps:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
